package artifact_structs

type Windows_System_WMIQuery struct {
	Caption                    string      `json:"Caption"`
	CommandLine                string      `json:"CommandLine"`
	CreationClassName          string      `json:"CreationClassName"`
	CreationDate               string      `json:"CreationDate"`
	CSCreationClassName        string      `json:"CSCreationClassName"`
	CSName                     string      `json:"CSName"`
	Description                string      `json:"Description"`
	ExecutablePath             string      `json:"ExecutablePath"`
	ExecutionState             interface{} `json:"ExecutionState"`
	Handle                     string      `json:"Handle"`
	HandleCount                int         `json:"HandleCount"`
	InstallDate                interface{} `json:"InstallDate"`
	KernelModeTime             string      `json:"KernelModeTime"`
	MaximumWorkingSetSize      int         `json:"MaximumWorkingSetSize"`
	MinimumWorkingSetSize      int         `json:"MinimumWorkingSetSize"`
	Name                       string      `json:"Name"`
	OSCreationClassName        string      `json:"OSCreationClassName"`
	OSName                     string      `json:"OSName"`
	OtherOperationCount        string      `json:"OtherOperationCount"`
	OtherTransferCount         string      `json:"OtherTransferCount"`
	PageFaults                 int         `json:"PageFaults"`
	PageFileUsage              int         `json:"PageFileUsage"`
	ParentProcessID            int         `json:"ParentProcessId"`
	PeakPageFileUsage          int         `json:"PeakPageFileUsage"`
	PeakVirtualSize            string      `json:"PeakVirtualSize"`
	PeakWorkingSetSize         int         `json:"PeakWorkingSetSize"`
	Priority                   int         `json:"Priority"`
	PrivatePageCount           string      `json:"PrivatePageCount"`
	ProcessID                  int         `json:"ProcessId"`
	QuotaNonPagedPoolUsage     int         `json:"QuotaNonPagedPoolUsage"`
	QuotaPagedPoolUsage        int         `json:"QuotaPagedPoolUsage"`
	QuotaPeakNonPagedPoolUsage int         `json:"QuotaPeakNonPagedPoolUsage"`
	QuotaPeakPagedPoolUsage    int         `json:"QuotaPeakPagedPoolUsage"`
	ReadOperationCount         string      `json:"ReadOperationCount"`
	ReadTransferCount          string      `json:"ReadTransferCount"`
	SessionID                  int         `json:"SessionId"`
	Status                     interface{} `json:"Status"`
	TerminationDate            interface{} `json:"TerminationDate"`
	ThreadCount                int         `json:"ThreadCount"`
	UserModeTime               string      `json:"UserModeTime"`
	VirtualSize                string      `json:"VirtualSize"`
	WindowsVersion             string      `json:"WindowsVersion"`
	WorkingSetSize             string      `json:"WorkingSetSize"`
	WriteOperationCount        string      `json:"WriteOperationCount"`
	WriteTransferCount         string      `json:"WriteTransferCount"`
}
